Repository MSA-Team4-Final/Front-end, pull requests merged in 2025-08, with the labels that each got.

#24 비밀번호 변경 추가
  src/App.vue
  src/components/auth/SignupHeader.vue
  src/router/index.js
  src/stores/auth.js
  src/views/auth/ResetPassword.vue
  src/views/auth/SignUpForm.vue
  src/views/auth/TermsOfService.vue
Labels: enhancement

#27 환율 계산기 화면 및 실시간 가격 추이 기능 구현
  src/views/ExchangeInfo/Calculator.vue
  src/views/ExchangeInfo/RateLookup.vue
Labels: enhancement

#29 fix: 환전, 친구 송금 수정 및 병합
  src/views/CurrentExchange/CurrentExchange.vue
  src/views/Remittance/Remittance.vue
Labels: enhancement, fix

#37 Feat/alarm
  src/components/MainPage.vue
  src/router/index.js
  src/views/ExchangeInfo/RateAlert.vue
  src/views/ExchangeInfo/RateLookup.vue
  src/views/News.vue
Labels: enhancement

#38 fix: 문의 페이지 수정
  src/stores/auth.js
  src/views/admin/Inquiries.vue
  src/views/admin/Remittances.vue
  src/views/support/InquiryList.vue
  src/views/support/InquiryWrite.vue
Labels: fix
