Repository MSA-Team4-Final/Front-end, pull requests merged in 2025-09, with the labels that each got.

#42 feat: 친구송금 거래내역, 환전 거래내역 추가 + 계좌 조회 헤더바 -> 마이페이지 이동
  src/components/HeaderBar.vue
  src/router/index.js
  src/views/Account/AccountDetail.vue
  src/views/Account/AccountView.vue
  src/views/Account/DepositWithdraw.vue
  src/views/CurrentExchange/CurrentExchange.vue
  src/views/CurrentExchange/CurrentExchangeDetail.vue
  src/views/MyPage.vue
  src/views/Remittance/FavoriteFriend.vue
  src/views/Remittance/Remittance.vue
  src/views/Remittance/RemittanceDetail.vue
Labels: enhancement

#43 feat: 환율 차트 UX 개선, AI 챗봇 화면 구성
  src/App.vue
  src/components/HeaderBar.vue
  src/components/chart/ExchangeRateChart.vue
  src/components/chatbot/Chatbot.vue
  src/views/ExchangeInfo/Calculator.vue
  src/views/ExchangeInfo/RateChart.vue
  src/views/ExchangeInfo/RateLookup.vue
Labels: enhancement

#47 feat: 충전/출금 개발 완료, 포멧팅 처리, 친구송금 오류, 추가 오류 처리중
  src/components/HeaderBar.vue
  src/components/MainPage.vue
  src/views/Account/AccountDetail.vue
  src/views/Account/AccountView.vue
  src/views/Account/DepositWithdraw.vue
  src/views/Account/DepositWithdrawHistory.vue
  src/views/CurrentExchange/CurrentExchange.vue
  src/views/CurrentExchange/CurrentExchangeDetail.vue
  src/views/MyPage.vue
  src/views/Remittance/FavoriteFriend.vue
  src/views/Remittance/Remittance.vue
  src/views/Remittance/RemittanceDetail.vue
Labels: enhancement, fix

#48 fix: 디테일 수정
  src/router/admin.js
  src/router/index.js
  src/stores/auth.js
  src/views/MyPage.vue
  src/views/admin/Settings.vue
  src/views/auth/SignUpForm.vue
  src/views/auth/SignupAccountSecurity.vue
  src/views/auth/SignupAgreement.vue
  src/views/auth/SignupIdentity.vue
  src/views/mypage/CalendarView.vue
  src/views/mypage/MyInfo.vue
  src/views/support/InquiryList.vue
Labels: fix
